# NumPy
NumPy (Numerical Python) is a powerful Python library used for mathematical and numerical operations. It provides a high-performance multidimensional array object and tools for working with these arrays.

## To install numpy
1. pip install numpy (in VS Code Terminal or cmd)
      ##### OR
2. !pip install numpy (in Jupyter Notebook)

## Why use Numpy?
1. Much faster than Python lists for numerical tasks
2. Used as the foundation for libraries like Pandas, TensorFlow and Scikit-learn
3. Makes matrix operations, statistics and data transformations easy and efficient

# NumPy Array
A NumPy array is a powerful data structure that stores elements of the same data type in a grid-like format. It is much faster and more efficient than Python lists for numerical operations.

### Creating Arrays:

In [228]:
import numpy as np

a = np.array([1,2,3])  # Form a list
b = np.zeros((2,3))    # Array of zeros
c = np.ones((3,3))     # Array of ones
d = np.arange(0,10,2)  # Range of numbers

# b and c are in the format (rows, column)

print(a)
print('\n')
print(b)
print('\n')
print(c)
print('\n')
print(d)

[1 2 3]


[[0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[0 2 4 6 8]


### Basic Array Operations:

#### 1. Indexing and Slicing:

In [216]:
arr = np.array([10,20,30,40])   # 1-D array
arr2 = np.array([[1,3,5],[2,4,6]])
print(arr[1])                   # 20
print('\n')
print(arr[1:3])                 # [20 30]
print('\n')
print(arr2)                     # [[1 3 5] [2 4 6]]

20


[20 30]


[[1 3 5]
 [2 4 6]]


#### 2. Array Shape and Dimensions:

In [218]:
print(arr.shape)    # returns (row,column)
print('\n')
print(arr.ndim)     # returns no. of dimensions
print('\n')
print(arr.size)     # returns total no. of elements
print('\n')
print(arr2.shape)
print('\n')
print(arr2.ndim)

(4,)


1


4


(2, 3)


2


#### 3. Reshaping Arrays

In [220]:
arr = np.array([[1,2],[3,4],[5,6]])   # 2-D array
print(arr.reshape(2,3))               # change the shape 
print('\n')
print(arr.ndim)

[[1 2 3]
 [4 5 6]]


2


#### 4. Data Types:

In [165]:
arr.dtype # returns the data type of elements

dtype('int32')

### Mathematical Operations:

#### 1. Element-wise Operations:

In [222]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)    # [5,7,9]
print('\n')
print(a * b)    # [4,10,18]
print('\n')
print(a ** 2)   # [1,4,9]

[5 7 9]


[ 4 10 18]


[1 4 9]


#### 2. Aggregate Functions:

In [224]:
arr = np.array([5,10,15])

print(np.sum(arr))     # 30
print('\n')
print(np.mean(arr))    # 10
print('\n')
print(np.min(arr))     # 5
print('\n')
print(np.max(arr))     # 15
print('\n')
print(np.std(arr))     # Standard Deviation

30


10.0


5


15


4.08248290463863


#### 3. Broadcasting (Simplified)

In [172]:
a = np.array([1,2,3])
a + 5                 # [6,7,8]

array([6, 7, 8])

# NumPy in Action:
Let's use NumPy in real-world scenario: analyzing temparature data

### Example: Calculate Average Weekly Temperature

In [182]:
import numpy as np

# Temparatures in °C for 7 days
temps = np.array([30.5,32.0,31.2,29.8,28.9,30.0,31.5])

# Average temperature
avg_temp = np.mean(temps)
print(f"Average Temp: {avg_temp:.1f} °C")

Average Temp: 30.6 °C


### Note: For ° -> press and hold Alt + 0176